name: Deploy

on:
  push:
    branches:
      - main

jobs:
  dist:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: List build contents (debug)
        run: ls -la ./dist

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
          retention-days: 1

  deploy:
    name: Deploy
    needs: dist
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: List available artifacts (debug)
        run: ls -la

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist

      - name: List dist contents after download (debug)
        run: ls -la ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
